### ISSUE TITLE
Question about variations and variationsChoices for OrderItems

### ISSUE THREAD

**Issue by jayhardee9** [wix/openrest4j#13]
Are the `variations` and `variationsChoices` properties of class `OrderItem` parallel arrays? That is, is `variationsChoices[0]` the choices selected for `variations[0]`?

**Comment by dleshem** [comment]
> Are the `variations` and `variationsChoices` properties of class `OrderItem` parallel arrays? That is, is `variationsChoices[0]` the choices selected for `variations[0]`?

Yes.

**Comment by jayhardee9** [comment]
Thanks, just wanted to double-check
